import type { Metadata } from "next";
import { ProgressProvider } from "@bprogress/next/pages";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import ProgressBarProdiver from "./providers/progress-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-200`}
      >
        <ProgressBarProdiver>
          <div className="flex flex-col min-h-screen max-w-[1200px] mx-auto bg-white text-sm">
            <Header />
            {children}
            <Footer />
          </div>
        </ProgressBarProdiver>
      </body>
    </html>
  );
}
