import ProgressBarProvider from "@/app/providers/progress-provider";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { DevTools } from "@/components/dev-tools";
// import { DevTools } from "@/components/dev-tools";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <ProgressBarProvider>
            <div className="flex flex-col min-h-screen max-w-[1200px] mx-auto text-sm">{children}</div>
            <DevTools />
          </ProgressBarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
